server:
  port: 7777

spring:
  application:
    name: @pom.artifactId@
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/microcent/mall/
          searchPaths: mall-config-repo