server:
  port: 8443
  servlet:
    context-path: /
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: tomcat

spring:
  profiles:
    active: dev,core,db
  jackson:
    serialization:
      indent-output: true
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    # 过滤字符编码
    encoding:
      charset: UTF-8
      enabled: true
      force: true

swagger:
  version: 1.0.0
  basePackage: cn.com.microcent.controller

logging:
  level:
    root:  INFO
    org.springframework:  INFO