server:
  port: 8000
  servlet:
    context-path: /

spring:
  profiles:
    active: dev,core,db
  jackson:
    serialization:
      indent-output: true
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
  jpa:
    hibernate:
      # 实体类有更新时，数据库表更新
      ddl-auto: update
    show-sql: true
    format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  http:
    # 过滤字符编码
    encoding:
      charset: UTF-8
      enabled: true
      force: true

swagger:
  version: 1.0.0
  basePackage: cn.com.microcent.controller

logging:
  level:
    root:  INFO
    org.springframework:  INFO