spring:
    application:
        name: monitor-server

server:
    port: 8764 #启动端口

eureka:
     instance:
        preferIpAddress: true
     client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
          defaultZone: http://localhost:1001/eureka/


